### ISSUE TITLE
I get BadImageFormatException at runtime

### ISSUE THREAD

**Issue by chester89** [AntShares/LevelDB.Net#4]
I downloaded latest Nuget last night and tried to write some data - instead I got BadImageFormatException.

**Comment by erikzhang** [comment]
It could be used on x64 platform only.

**Comment by chester89** [comment]
Does that mean AnyCPU isn't good enough?

2016-03-01 10:11 GMT+03:00 Erik Zhang <notifications@github.com>:

> It could be used on x64 platform only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AntShares/LevelDB.Net/issues/4#issuecomment-190585695>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by erikzhang** [comment]
LevelDB.Net is a wapper of leveldb based on C++/CLI, which does not support AnyCPU.

**Comment by chester89** [comment]
Ok, understood. Closes #4

2016-03-01 10:26 GMT+03:00 Erik Zhang <notifications@github.com>:

> LevelDB.Net is a wapper of leveldb based on C++/CLI, which does not
> support AnyCPU.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AntShares/LevelDB.Net/issues/4#issuecomment-190590880>
> .
>



-- 
Yours faithfully,
Gleb
